# Generated by Django 5.2 on 2025-05-19 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('brand', models.CharField(max_length=128)),
                ('people_capacity', models.IntegerField()),
                ('characteristics', models.TextField()),
                ('release_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='LongRouteName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=64)),
                ('bus_stop_name', models.CharField(max_length=128)),
                ('bs_num', models.IntegerField()),
                ('bs_num_reverse', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_num', models.CharField(max_length=16)),
                ('short_route_name', models.TextField()),
                ('city', models.CharField(max_length=128)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='main.bus')),
                ('long_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='long_route_name', to='main.longroutename')),
            ],
        ),
    ]
