# Generated by Django 5.2 on 2025-05-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='route',
            name='bus',
        ),
        migrations.RemoveField(
            model_name='route',
            name='long_route',
        ),
        migrations.AddField(
            model_name='route',
            name='bus',
            field=models.ManyToManyField(related_name='buses', to='main.bus'),
        ),
        migrations.AddField(
            model_name='route',
            name='long_route',
            field=models.ManyToManyField(related_name='long_route_name', to='main.longroutename'),
        ),
    ]
